=== dgray16/chnu_xml/3/file.dtd
<!ELEMENT progress (student)*>
        <!ELEMENT student (name, group, book)>

        <!ELEMENT name (#PCDATA)>
        <!ELEMENT group (#PCDATA)>

        <!ELEMENT book (#PCDATA)>
                <!ATTLIST book mark1 CDATA #REQUIRED>
                <!ATTLIST book mark2 CDATA #REQUIRED>
                <!ATTLIST book mark3 CDATA #REQUIRED>
                <!ATTLIST book mark4 CDATA #REQUIRED>

=== dgray16/chnu_xml/3/students.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/css" href="styles.css"?>
<!DOCTYPE progress SYSTEM "file.dtd">


<progress>
    <student>
        <name>Perebykisvkiy V.V</name>
        <group>443SK</group>
        <book mark1="5" mark2="4" mark3="3" mark4="4">
            0987654321
        </book>
    </student>
    <student>
        <name>Tester Test</name>
        <group>441</group>
        <book mark1="3" mark2="3" mark3="3" mark4="4">
            1234567890
        </book>
    </student>
</progress>
